### ISSUE TITLE
this library didn't work for me in C++

### ISSUE THREAD

**Issue by lisn3188** [testo/toolbox_fluegas#6]
I used VS2019, created a C++ project, added the dll file and added the header file, successfully opened the T350 via USB, and read the correct serial number. But when I want to read the sensor reading, it fails and the returned row and column are 1, 0 respectively.
Below is my code, in addition, it is possible to read sensor readings using TestoOnlineReader.exe.

int main()
{
    void* hTesto330;
    int i,col,row;
    unsigned char buf[128];
    int len = Testo330GetNumberOfUsbDevices();
    if (len > 0) {
        printf("find %d  ", len);
    }
    else {
        printf("no Devices \n");
        return 0;
    }
    for (i = 0; i < len; i++) {
        printf("device%d SN = %d\n", i, Testo330GetUsbSerialNumber(i));
    }
    hTesto330 = Testo330Open(0,1,0);
    if (hTesto330 == 0) {
        printf("open Device Error\n");
        return 0;
    }

    Testo330GetAllProtocols(hTesto330);
    len = Testo330GetNumProtocols(hTesto330);
    printf("NumProtocols = %d\n",len);
    Testo330ReadProtocol(hTesto330, 0);
    col = Testo330GetNumColumns(hTesto330);
    row = Testo330GetNumRows(hTesto330);
    printf("col = %d   Row = %d \n",col,row);
    
    for (i = 0; i < col; i++) {
        memset(buf, 0, sizeof(buf));
        Testo330GetColumnName(hTesto330,i,buf);
        printf("col %d Name =%s \n",i,buf);
    }

    Testo330Close(hTesto330);
    printf("Close Devices \n");
    return 0;
}

the output is blow
![image](https://user-images.githubusercontent.com/68287198/172087655-6e74802d-a7aa-441f-80b3-b0c168f3ef2e.png)

**Comment by FlominatorTM** [comment]
TestoOnlineReader reads live sensor values. Your code reads stored protocols from the device. You need to use the online values functions in order to retrieve live sensor values.

**Comment by lisn3188** [comment]
Thanks a lot, I have successfully read the sensor value

**Comment by FlominatorTM** [comment]
I'm happy that it works. Thanks for the feedback
