### ISSUE TITLE
Toolbox Integration Issue

### ISSUE THREAD

**Issue by rylearns** [testo/toolbox_fluegas#7]
Good day, I'm developing some code that uses this toolbox but have hit a bit of a wall. 

For some context, I'm using VS2022 and have created some basic C++ code. I've added the proper header and DLL's. My program is able to compile and run but I get this error.

" Unhandled exception at 0x629E5391 (testo330Base.dll) in TestoIntegrationV3.exe: 0xC0000005: Access violation reading location 0x03BC19D9." 

![image](https://github.com/testo/toolbox_fluegas/assets/142119830/050dcd30-4d81-4aac-8d6f-6da0b9563663)

Below you'll find the code I've written:

int main()
{
    void* hTesto330;              // Pointer to a device handle
    int i;

    int num = Testo330GetNumberOfUsbDevices(); 

    if (num > 0) {
        printf("We found %d devices", num);;  // Print the number of found devices
    }
    else {
        printf("No devices were found \n");  // Print a message if no devices are found
        return 0;                 // Exit the program
    }

    // Iterate through each detected device and print its serial number
    for (i = 0; i < num; i++) {
        printf("device%d SN = %d\n", i, Testo330GetUsbSerialNumber(i));
    }

    // Open a Testo 330 device
    hTesto330 = Testo330Open(0, 1, 0);

    if (hTesto330 == 0) {
        printf("Error when opening device\n");  // Print an error message if device opening fails
        return 0;                        
    }
    // Close the Testo 330 device
    Testo330Close(hTesto330);
    printf("Close Devices \n");

    return 0; 
}

I'd appreciate any guidance or advice on the best way to address this issue.

**Comment by FlominatorTM** [comment]
Hello and thanks for reaching out, some questions without any further analysis of your code for the moment:

- did you install the USB driver?
- did you compile for 32 bits?
- does the sample/online reader run?
- does the log state anything?

Kind regards from Black Forest

**Comment by rylearns** [comment]
Hey!

Here are some answers to your questions:

- _did you install the USB driver?_ -> Yes
- _did you compile for 32 bits?_ -> Yes
- _does the sample/online reader run?_ ->Yes she works without any issue
- _does the log state anything?_ -> Yes, bellow is what the %TEMP% file contains.


14.08.2023 14:36:43 === Start ===
14.08.2023 14:36:43 Testo330GetNumberOfUsbDevices
14.08.2023 14:36:43 GetNumberOfDevicesFTDI; ProductID 2; number of devices 0, error code 0
14.08.2023 14:36:44 GetNumberOfDevicesFTDI; ProductID 16; number of devices 1, error code 0

**Comment by FlominatorTM** [comment]
It looks like you're using a testo 340, but the next log message that connection is established is missing. Weird. This requires further analysis and dialog.

Can you please reach out to us via _helpdeskInstrumentation _the_usual_sign testo.de_ by including a link to this issue?

**Comment by rylearns** [comment]
Sounds good. Sending an email shortly.

**Comment by FlominatorTM** [comment]
I still didn't receive any ticket. Did you send it? Please contact me directly at fstraub@testo.de

**Comment by rylearns** [comment]
Hey, 
The request was sent on August 18 and I've gotten a ticket #. I'll forward you that information via email.
